#!/bin/sh

DAEMON="/usr/bin/wlan0-bootstrap"
CONFIG="/etc/wlan0-bootstrap/config.toml"
PIDFILE="/var/run/wlan0-bootstrap.pid"
LOGFILE="/var/log/wlan0-bootstrap.log"

start() {
	printf "Starting wlan0-bootstrap: "
	mkdir -p /data/wlan0-bootstrap /run/wlan0-bootstrap
	start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON" -- --config "$CONFIG" >>"$LOGFILE" 2>&1
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping wlan0-bootstrap: "
	start-stop-daemon -K -p "$PIDFILE"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
